# Generated by Django 5.0.6 on 2024-07-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='lesons/audio/')),
                ('image', models.ImageField(upload_to='lesons/images/')),
            ],
        ),
    ]
