# Generated by Django 5.0.6 on 2024-07-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_lesons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesons',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='lesons',
            old_name='audio_file',
            new_name='src',
        ),
    ]
